name: Rust

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Prepare
      run: sudo apt-get install libgtk-4-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
